import Image from 'next/image'
import React from 'react'
import { storiesClimateChange } from '@/api/api'
import Slider from '@/components/sliderStories'

export const metadata = {
  title: 'Balancing Act',
  description: 'Balancing Act | SMC Sustainability',
}

export default function Index() {
  return (
    <section className='article-container'>
      <div className='block-content'>
        <article className='article'>
          <section className='description-container'>
            <div className='full-img'>
              <Image src="page/balancing_act_banner.png" width={1080} height={568} alt='Balancing Act' />
            </div>

            <h1 className='green'>Balancing Act</h1>

            <p>
              SMGP maintains a diversified portfolio
              of both traditional and renewable power
              facilities. Even at the beginning of
              implementing our next-stage strategies
              to achieve a lower carbon future—such as
              investing in battery storage and renewable
              capacities on our way to net zero by 2050—coal
              power remains an indispensable
              resource for the Philippines in the
              foreseeable future.
            </p>

            <Image style={{ borderRadius: '0' }} src="page/ba1.png" width={400} height={471} alt='Balancing Act' />

            <p>
              We have long recognized the crucial
              importance of balancing our developing
              nation’s need for reliable and affordable
              baseload energy with the need to minimize
              our environmental impact. Our approach,
              particularly for coal power, has been to
              utilize the latest technologies that can
              drastically cut harmful emissions. </p>

            <h3 className='green'>HELE Technology</h3>
            <p>
              HELE technologies are a type of cutting-edge
              coal technology designed to increase production
              efficiency while lowering the GHG and non-GHG
              emissions per amount of power generated by our
              coal-fired power plants. </p>

            <p>
              It can be achieved through a supercritical, ultrasupercritical, or advanced ultra-supercritical
              technology that allows the power plants to run
              at higher temperatures and pressures to bring
              about more thorough fuel combustion, resulting in
              increased efficiency and lower CO2 emissions. This
              enables coal-fired power plants to use less fuel to
              produce the same amount of energy, ultimately
              resulting in minimized environmental impact.
            </p>

            <Image style={{ borderRadius: '0' }} src="page/ba2.png" width={410} height={550} alt='Balancing Act' />

            <p>
              HELE technologies also encompass other
              advanced technologies, such as improved coal
              drying and cleaning processes, advanced air
              pollution control systems that aids in lowering
              sulfur and nitrogen oxide emissions, and improved
              materials for the high-temperature components in
              facilities.
            </p>


            <h3 className='green'>CFB Technology</h3>
            <p>
              Meanwhile, circulating fluidized bed (CFB)
              technology, used in the combustion of solid fuels,
              such as coal and biomass, is another way we
              produce power in a more environment-friendly
              manner.
            </p>

            <p>
              In a CFB, solid fuel is introduced into a furnace
              with bed material, such as sand or other
              particulate matter. Fans supply excess oxygen
              into the furnace so that complete combustion can
              take place. This causes the bed material to flow
              continuously inside the furnace and be kept in
              suspension by the flow of hot gases produced by
              the combustion of the fuel. This creates a fluidized
              bed resembling boiling liquid, allowing solid fuel
              particles to move freely, promoting mixing and
              heat transfer. The hot gases are then circulated
              back through the bed to maintain the fluidized
              state, hence the name “circulating fluidized bed.”
            </p>


            <Image style={{ borderRadius: '0' }} src="page/ba3.png" width={410} height={550} alt='Balancing Act' />

            <p>
              Improving combustion efficiency and lowering
              emissions of pollutants like SOx and NOx are some
              of the main benefits of CFB. Additionally, CFBs are
              a flexible and eco-friendly technology because they
              can be easily retrofitted with scrubbers to remove
              pollutants. CFB’s operating furnace temperature
              is between 850 and 950 degrees Celsius, which
              is just enough for complete combustion. This
              means that NOx cannot be produced in the furnace
              because that would require furnace temperatures
              to reach 1200 to 1300 degrees Celsius. In addition,
              limestone is injected into the system to capture the
              generated SOx as a byproduct of the combustion
              process.
            </p>

            <p>
              HELE and CFB Technologies have been critical
              to minimizing the impacts that our coal power
              facilities have on the environment. Our Limay,
              Bataan and Malita, Davao Occidental plants, with
              600 MW and 300 MW capacities, respectively,
              are CFBs. A third CFB facility built in Mariveles,
              Bataan, with an installed capacity of 600 MW, is
              also set to come online in 2023.
            </p>

            <p>
              In Masinloc, SMGP operates a 335 MW
              supercritical coal-fired power plant. Construction
              is also ongoing on another supercritical plant,
              which would use less fuel than the conventional
              power plants, for the optimum generated amount
              of electricity.
            </p>

            <Slider storiesItem={storiesClimateChange} />

          </section>
        </article>
      </div>
    </section>
  )
}
